; WARNING: Don't edit this file. All change will be removed after each app upgrade
; 
; https://codeberg.org/forgejo/forgejo/src/branch/forgejo/custom/conf/app.example.ini
APP_NAME = Forgejo
RUN_USER = {{ app }}
RUN_MODE = prod
WORK_PATH = {{ install_dir }}

[database]
DB_TYPE = postgres
HOST = 127.0.0.1:5432
NAME = {{ db_name }}
USER = {{ db_user }}
PASSWD = {{ db_pwd }}
SSL_MODE = disable
LOG_SQL = false

[repository]
ROOT = {{ data_dir }}/repositories
FORCE_PRIVATE = false
MAX_CREATION_LIMIT = {{ max_creation_limit }}

[admin]
DISABLE_REGULAR_ORG_CREATION = {{ disable_regular_org_creation }}

[server]
DOMAIN = {{ domain }}
HTTP_PORT = {{ port }}
HTTP_ADDR = 127.0.0.1
ROOT_URL = https://{{ domain }}{{ path }}
DISABLE_SSH = false
SSH_PORT = {{ ssh_port }}
OFFLINE_MODE = false
APP_DATA_PATH = {{ data_dir }}/data
LANDING_PAGE = explore
LFS_START_SERVER = {{ lfs_enable }}
LFS_JWT_SECRET = {{ lfs_jwt_secret }}
LFS_ALLOW_PURE_SSH = {{ lfs_ssh_support }}
LOCAL_ROOT_URL = http://127.0.0.1:{{ port }}/

[mailer]
ENABLED = true
SMTP_ADDR = localhost
SMTP_PORT = 587
PROTOCOL = smtp+starttls
FROM = "Forgejo" <{{ app }}@{{ domain }}>
USER = {{ app }}
PASSWD = {{ mail_pwd }}
FORCE_TRUST_SERVER_CERT = true

[email.incoming]
ENABLED = true
REPLY_TO_ADDRESS = {{ app }}+%{token}@{{ domain }}
HOST = localhost
PORT = 993
USE_TLS = true
SKIP_TLS_VERIFY = true
USERNAME = {{ app }}
PASSWORD = {{ mail_pwd }}

[service]
REGISTER_EMAIL_CONFIRM = {{ register_email_confirm }}
REGISTER_MANUAL_CONFIRM = {{ register_manual_confirm }}
DISABLE_REGISTRATION = {{ disable_registration }}
ENABLE_NOTIFY_MAIL = {{ enable_notify_mail }}
SHOW_REGISTRATION_BUTTON = {{ show_registration_button }}
ENABLE_REVERSE_PROXY_AUTHENTICATION = true
ENABLE_REVERSE_PROXY_AUTO_REGISTRATION = true
ENABLE_REVERSE_PROXY_EMAIL = true
DEFAULT_KEEP_EMAIL_PRIVATE = {{ default_keep_email_private }}

[service.explore]
REQUIRE_SIGNIN_VIEW = {{ require_signin_view }}
DISABLE_USERS_PAGE = {{ disable_users_page }}
DISABLE_ORGANIZATIONS_PAGE = {{ disable_organizations_page }}
DISABLE_CODE_PAGE = {{ disable_code_page }}

[ui]
SHOW_USER_EMAIL = {{ show_user_email }}

[picture]
AVATAR_UPLOAD_PATH = {{ data_dir }}/data/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = {{ data_dir }}/data/repo-avatars

[attachment]
PATH = {{ data_dir }}/attachments

[mirror]
ENABLED = {{ mirror_enabled }}
DISABLE_NEW_PULL = {{ mirror_disable_new_pull }}
DISABLE_NEW_PUSH = {{ mirror_disable_new_push }}
DEFAULT_INTERVAL = {{ mirror_default_interval }}
MIN_INTERVAL = {{ mirror_min_interval }}

[session]
PROVIDER = memory

[log]
MODE = file
LEVEL = Info
ROOT_PATH = /var/log/{{ app }}
LOGGER_ACCESS_MODE = 
LOGGER_ROUTER_MODE = router
LOGGER_XORM_MODE = xorm

[log.file]
FILE_NAME = forgejo.log

[log.router]
MODE = file
FILE_NAME = router.log
LEVEL = Warn

[log.xorm]
MODE = file
FILE_NAME = xorm.log
LEVEL = Warn

[security]
INSTALL_LOCK = true
SECRET_KEY = {{ secret_key }}
REVERSE_PROXY_TRUSTED_PROXIES = 127.0.0.0/8,::1/128
INTERNAL_TOKEN = {{ internal_token }}
REVERSE_PROXY_AUTHENTICATION_USER = YNH_USER

[oauth2]
JWT_SECRET = {{ oauth2_jwt_secret }}

[federation]
ENABLED = {{ federation_enabled }}

[indexer]
REPO_INDEXER_ENABLED = {{ repos_indexer_enabled }}
REPO_INDEXER_PATH = indexers/repos.bleve
MAX_FILE_SIZE = 1048576
REPO_INDEXER_INCLUDE = 
REPO_INDEXER_EXCLUDE = resources/bin/**

[actions]
ENABLED = {{ actions_enabled }}
{% if webhook_allowed_hosts != '' %}

[webhook]
ALLOWED_HOST_LIST = {{ webhook_allowed_hosts }}

{% endif %}[cron.sync_external_users]
ENABLED = true
RUN_AT_START = true
SCHEDULE = @every 30m
UPDATE_EXISTING = true
{% if migrations_allowed_domains != '' %}

[migrations]
ALLOWED_DOMAINS = {{ migrations_allowed_domains }}
{% endif %}